name: Skyrim Inventory Management Frontend CI

on:
  push:
    branches: [ main, 30-game-model ]
  pull_request:
    branches: [ main, 30-game-model ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node Modules
      run: yarn
    - name: Run tests
      run: yarn test
